name: ids-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pandas
  - pip:
      - azureml-inference-server-http
      - scikit-learn==1.6.1
      - numpy==2.0.2
      - joblib