name: sklearn-env
description: "Environnement Azure ML avec Scikit-learn et Pandas"
image: mcr.microsoft.com/azureml/minimal-ubuntu20.04-py39-cpu-inference:latest
dependencies:
  - python=3.9
  - pip
  - pip:
      - azureml-inference-server-http
      - azureml-defaults
      - scikit-learn==1.6.1
      - pandas
      - numpy==2.0.2
      - joblib