name: sklearn-env
description: "Environnement Azure ML avec Scikit-learn et Pandas"
image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
dependencies:
  - python=3.8
  - pip
  - pip:
      - azureml-defaults
      - scikit-learn
      - pandas
      - numpy
      - joblib