$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: ids-pipeline
description: Pipeline IDS - Preprocessing + Training
compute: azureml:clusterids

jobs:
  preprocess_data:
    type: command
    component: ./preprocess_component.yml
    inputs:
      raw_data: azureml:dataset_honeytrap:1  # Lien direct vers le dataset
    outputs:
      preprocessed_data:
        mode: rw_mount

  train_model:
    type: command
    component: ./train_component.yml
    inputs:
      input_data: ${{parent.jobs.preprocess_data.outputs.preprocessed_data}}
    outputs:
      output_model:
        mode: rw_mount
