$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_model
display_name: Train IDS Models
version: 1
type: command
inputs:
  input_data:
    type: uri_folder
outputs:
  output_model:
    type: uri_folder
code: .
environment: azureml:sklearn-env:1
command: >-
  python train.py
  --input_data ${{inputs.input_data}}
  --output_model ${{outputs.output_model}}